# Generated by Django 6.0.5 on 2026-05-19 09:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('position', models.CharField(choices=[('director', 'Директор'), ('manager', 'Менеджер'), ('designer', 'Дизайнер'), ('craftsman', 'Мастер'), ('accountant', 'Бухгалтер'), ('logist', 'Логист'), ('other', 'Другое')], max_length=50, verbose_name='Должность')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Формат: +375 (29) XXX-XX-XX', regex='^\\+375 \\(\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('hire_date', models.DateField(verbose_name='Дата найма')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание обязанностей')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department', verbose_name='Отдел')),
                ('managed_clients', models.ManyToManyField(blank=True, related_name='managers', to='clients.client', verbose_name='Закреплённые клиенты')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
