version: '3.9'

services:

  db:
    image: postgres:16-alpine
    
    environment:
      POSTGRES_DB: furniture_factory      
      POSTGRES_USER: furniture_user       
      POSTGRES_PASSWORD: furniture_pass   
    
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:

    build: .

    ports:
      - "8000:8000"

    environment:
      DEBUG: "True"
      SECRET_KEY: "my-secret-key-for-dev"

      DATABASE_URL: postgresql://furniture_user:furniture_pass@db:5432/furniture_factory

    depends_on:
      - db

    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:   