services:
  - type: web
    name: furniture-factory
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput --settings=furniture_factory.settings_prod
      python manage.py migrate --settings=furniture_factory.settings_prod
    startCommand: gunicorn furniture_factory.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: furniture_factory.settings_prod
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: furniture-db
          property: connectionString
      - key: DEBUG
        value: "False"
      - key: LOG_LEVEL
        value: WARNING

databases:
  - name: furniture-db
    databaseName: furniture_factory
    user: furniture_user
