# Generated by Django 6.0.5 on 2026-05-19 09:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(max_length=20, unique=True, verbose_name='Код клиента')),
                ('company_name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Формат: +375 (29) XXX-XX-XX', regex='^\\+375 \\(\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон')),
                ('city', models.CharField(choices=[('minsk', 'Минск'), ('gomel', 'Гомель'), ('mogilev', 'Могилев'), ('vitebsk', 'Витебск'), ('grodno', 'Гродно'), ('brest', 'Брест'), ('other', 'Другой')], default='minsk', max_length=50, verbose_name='Город')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения контактного лица')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['company_name'],
            },
        ),
    ]
